#!/bin/bash
# $Id: blacklist,v 1.122 2018/06/01 18:42:47 fulford Exp $
# $Source: /src/admin/usr/local/etc/RCS/blacklist,v $
# $Revision: 1.122 $
# Author C W Fulford.
# Copyright 2017 (c) C W Fulford.
# Licensed for public use under the LGPL, .
# For assistance contact fulford@fulford.net 0793 572 8612
########################################################################
cmd=`basename $0`

config=/usr/local/etc/blacklist.cf
ver=`echo "$Id: blacklist,v 1.122 2018/06/01 18:42:47 fulford Exp $"|awk '{print $3,$4,$5}'`
sysadmin=fulford@fulford.net

syntax="$cmd  [-l] | [-V]"
while [ $# -gt 0 ] ;do
	case $1 in 
		-l) log=:;shift;;			
		-V) echo "$cmd $Revision: 1.122 $ $Date: 2018/06/01 18:42:47 $"|awk '{print $1,$3,$6}';exit;;  
	esac
done
export ADMINHOST=admin
export ERROR=0
export MAILHOST=mail
export LOG=/var/log/blacklist/blacklist.log
export TARGET=access
export SRCDIR=/src/admin/etc/mail
# CityLinux keeps RCS records of critical files in separate file system 
export TARGETDIR=/etc/mail
export SRC=$SRCDIR/$TARGET
export DEST=$TARGETDIR/$TARGET
export TMP=/tmp/${TARGET}

_error () { echo "$cmd: error near line $1";  ;}
_end () { echo -n 'Press "Return" to continue';read ought </dev/tty ;}

address=`grep "^Return-Path: " | sed -e 's/Return-Path: <\([^>]*\)>/\1/'`
echo "address = $address"

domain=`echo $address|sed -e 's/[^@]*@\(.*$\)/\1/g'`
echo "domain = $domain"

# Spare legitimate domains 
ldomains=`awk <$config '{printf "%s ",$1}'`
if echo $address |grep -s fulford.net; then
	mailx -s "blacklist ALERT" $sysadmin <<- .
		Blackist has found fulford.net in the Return-Path
		$address
	.
	echo "Blacklist has found fulford.net in the Return-Path:"
fi
blacklist=$domain
for ld in $ldomains ;do
 	if [ "$domain" == $ld ] ;then
		blacklist=$address
	fi
done
echo -n "Blacklist ${blacklist} [y/n]? "
read answer <&2 
answer=${answer:-"y"}
if [ "$answer" == "y" ];then
	
	export BLACKLIST=`echo $blacklist|sed -e 's/\(.*\)/\1\t REJECT/'`
	id	
	ssh $ADMINHOST "
		set -x
		echo \"pwd = `pwd`\"
		echo $ADMINHOST
		echo \"SRCDIR = $SRCDIR\"
		cd $SRCDIR
		hostname	
		co -l -q $TARGET
		ERROR=$? 
		echo $BLACKLIST >$TMP
		cat $TARGET >>$TMP
		# makemap will fail if there are duplicate entries in the
		# access file
		cat $TMP|sort -u > $TARGET  #2>/dev/null
		cat $TARGET|ssh $MAILHOST sudo dd of=$DEST
		/usr/bin/ci -m -q $TARGET 
		ERROR=$?
		rm $TMP
		exit $ERROR
		"
	[ $ERROR -gt 0 ] && { _error $LINENO; _end ;}
	ssh $MAILHOST "
		set -x
		hostname
		echo $TARGETDIR
		echo \"`date`: $BLACKLIST\" >>$LOG
		cd $TARGETDIR 
		sudo /usr/bin/make access.db
		sudo /etc/rc.d/rc.sendmail restart
		sudo logger  -p mail.info -t blacklist \"$blacklist blacklisted\"
		"
	
	echo "$blacklist blacklisted."
else
	echo "$blacklist has not been blacklisted."
fi
_end
