#!/bin/bash
# $Id: blacklist,v 1.13 2017/07/20 10:38:53 fulford Exp $
# $Source: /src/admin/usr/local/etc/RCS/blacklist,v $
# $Revision: 1.13 $
# Author C W Fulford.
# Copyright 2017 (c) C W Fulford.
# Licensed for public use under the LGPL, .
# For assistance contact fulford@fulford.net 0793 572 8612
########################################################################
cmd=`basename $0`
ver=`echo "$Id: blacklist,v 1.13 2017/07/20 10:38:53 fulford Exp $"|awk '{print $3,$4,$5}'`
syntax="$cmd  [-l] | [-V]"
while [ $# -gt 0 ] ;do
	case $1 in 
		-l) log=:shift;;			
		-V) echo "$cmd $Revision: 1.13 $ $Date: 2017/07/20 10:38:53 $"|awk '{print $1,$3,$6}';exit;;  
	esac
done
TARGET=access
SRCDIR=/src/admin/etc/mail
# CityLinux keeps RCS records of critical files in separate file system 
TARGETDIR=/etc/mail
SRC=$SRCDIR/$TARGET
export DEST=$TARGETDIR/$TARGET
cd $SRCDIR
TMP=/tmp/${TARGET}$$
# The script will be running with the daemon id, ensure daemon has RCS
# access to the source file eg. "rcs -a daemon access"
co -l $TARGET
cp $TARGET $TMP
list=`grep ^From: |sed -e 's/.*<\(.*\)>/\1/g'|
	grep .*@.*\.[a-z]*|
	sed -e 's/\(.*\)/\1 REJECT/'|
	tee -a $TMP`
# makemap will fail if there are duplicate entries in the access file
uniq $TMP >$SRC
ci $TARGET
# We need to checkout access again to be able to copy it.
co $TARGET
# Ensure sudoers is configured to enable daemon to carry out the exact command
# as below after the variables have been expanded. 
sudo /bin/cp $TARGET $DEST
cd $TARGETDIR 
sudo /usr/bin/make access.db 
[ $log ] logger -t blacklist $list blacklisted
rm $TMP
