#!/bin/bash
# $Id: blacklist,v 1.21 2017/07/21 09:40:05 fulford Exp $
# $Source: /src/admin/usr/local/etc/RCS/blacklist,v $
# $Revision: 1.21 $
# Author C W Fulford.
# Copyright 2017 (c) C W Fulford.
# Licensed for public use under the LGPL, .
# For assistance contact fulford@fulford.net 0793 572 8612
########################################################################
cmd=`basename $0`
ver=`echo "$Id: blacklist,v 1.21 2017/07/21 09:40:05 fulford Exp $"|awk '{print $3,$4,$5}'`
syntax="$cmd  [-l] | [-V]"
while [ $# -gt 0 ] ;do
	case $1 in 
		-l) log=:;shift;;			
		-V) echo "$cmd $Revision: 1.21 $ $Date: 2017/07/21 09:40:05 $"|awk '{print $1,$3,$6}';exit;;  
	esac
done
TARGET=access
SRCDIR=/src/admin/etc/mail
# CityLinux keeps RCS records of critical files in separate file system 
TARGETDIR=/etc/mail
SRC=$SRCDIR/$TARGET
export DEST=$TARGETDIR/$TARGET
cd $SRCDIR
TMP=/tmp/${TARGET}$$
# The script will be running with the daemon id, ensure daemon has RCS
# access to the source file eg. "rcs -a daemon access"
sudo co -l -q $TARGET
cp $TARGET $TMP
list=`grep ^From: |sed -e 's/.*<\(.*\)>/\1/g'|
	grep .*@.*\.[a-z]*|
	sed -e 's/\(.*\)/\1 REJECT/'|
	tee -a $TMP`
# makemap will fail if there are duplicate entries in the access file
cat $TMP|sort -u >$SRC
# Ensure sudoers is configured to enable daemon to carry out the exact commands
# as below after the variables have been expanded. 
sudo /bin/cp $TARGET $DEST
sudo ci -m $TARGET
cd $TARGETDIR 
sudo /usr/bin/make access.db 
[ $log ] && logger -t blacklist $list blacklisted
rm $TMP
