.TH BLACKLIST 8l "20 July r1.12
.SH NAME
.B blacklist
- updates the \fI/etc/mail/access.db\fR database.
.SH SYNOPSIS
<cmd>|\fBblacklist [\fB-l\fR] 
.br
.SH AVAILABILITY
.B blacklist
is a Bourne shell script which should work equally well on all versions of UNIX
and Linux.
.SH DESCRIPTION
.B blacklist
is designed to be put on a pipe recieving e-mail messages. It may be invoked
manually see EXAMPLES but is best used used automatically to process messages
bounced to the \fIblacklist\fR user.
.SH OPTIONS
.TP 5
.B -l
turns on logging using the 
.B syslog
facility. 
.SH EXAMPLES
The following line is added to the "\fI/etc/mail/aliases\fR" file. Logging
is enabled.
.nf
.ft CW
blacklist:	"|/usr/local/etc/blacklist -l"
.ft R
.fi
.nf
.ft CW
cat <mailbox> |/usr/local/etc/blacklist
.LP
.SH BUGS
None known
.SH Files
.IR /etc/mail/access
.IR /etc/mail/access.db
.SH AUTHOR
Clifford W Fulford, City Linux. Contact fulford@fulford.net or +44 (0)793 572 8612
